//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MacroUO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MacroUO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while attaching to the client input thread. Retry using a macro without modifiers..
        /// </summary>
        internal static string ErrorClientInput {
            get {
                return ResourceManager.GetString("ErrorClientInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected client instance cannot be found. Please, perform a new scan..
        /// </summary>
        internal static string ErrorClientNone {
            get {
                return ResourceManager.GetString("ErrorClientNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected client instance cannot be found..
        /// </summary>
        internal static string ErrorClientSome {
            get {
                return ResourceManager.GetString("ErrorClientSome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file &quot;Macros.xml&quot; is either missing or malformed..
        /// </summary>
        internal static string ErrorPresetsFile {
            get {
                return ResourceManager.GetString("ErrorPresetsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized key for preset macro &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorPresetsKey {
            get {
                return ResourceManager.GetString("ErrorPresetsKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while saving the preset macros..
        /// </summary>
        internal static string ErrorPresetsSave {
            get {
                return ResourceManager.GetString("ErrorPresetsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is empty..
        /// </summary>
        internal static string ErrorStringEmpty {
            get {
                return ResourceManager.GetString("ErrorStringEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string is not a member of the specified enumeration..
        /// </summary>
        internal static string ErrorStringEnumerationMember {
            get {
                return ResourceManager.GetString("ErrorStringEnumerationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No string split separators have been provided..
        /// </summary>
        internal static string ErrorStringSeparators {
            get {
                return ResourceManager.GetString("ErrorStringSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unhandled exception has occurred and the application must be terminated..
        /// </summary>
        internal static string ErrorUnhandledException {
            get {
                return ResourceManager.GetString("ErrorUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset macros have been modified and reloading them will revert all the current changes. Do you want to proceed?.
        /// </summary>
        internal static string QuestionPresetsModified {
            get {
                return ResourceManager.GetString("QuestionPresetsModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset macros have been successfully reloaded..
        /// </summary>
        internal static string SuccessPresetsReload {
            get {
                return ResourceManager.GetString("SuccessPresetsReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string TextAdd {
            get {
                return ResourceManager.GetString("TextAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALT.
        /// </summary>
        internal static string TextAlt {
            get {
                return ResourceManager.GetString("TextAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        internal static string TextClients {
            get {
                return ResourceManager.GetString("TextClients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Clients Found.
        /// </summary>
        internal static string TextClientsEmpty {
            get {
                return ResourceManager.GetString("TextClientsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse.
        /// </summary>
        internal static string TextCollapse {
            get {
                return ResourceManager.GetString("TextCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string TextCopy {
            get {
                return ResourceManager.GetString("TextCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CTRL.
        /// </summary>
        internal static string TextCtrl {
            get {
                return ResourceManager.GetString("TextCtrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay:.
        /// </summary>
        internal static string TextDelay {
            get {
                return ResourceManager.GetString("TextDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string TextDetails {
            get {
                return ResourceManager.GetString("TextDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand.
        /// </summary>
        internal static string TextExpand {
            get {
                return ResourceManager.GetString("TextExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string TextHide {
            get {
                return ResourceManager.GetString("TextHide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key:.
        /// </summary>
        internal static string TextKey {
            get {
                return ResourceManager.GetString("TextKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macro.
        /// </summary>
        internal static string TextMacro {
            get {
                return ResourceManager.GetString("TextMacro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifiers:.
        /// </summary>
        internal static string TextModifiers {
            get {
                return ResourceManager.GetString("TextModifiers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TextOptions {
            get {
                return ResourceManager.GetString("TextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset Macros.
        /// </summary>
        internal static string TextPresetMacros {
            get {
                return ResourceManager.GetString("TextPresetMacros", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Preset Macros Found.
        /// </summary>
        internal static string TextPresetsEmpty {
            get {
                return ResourceManager.GetString("TextPresetsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Preset Macro Selected.
        /// </summary>
        internal static string TextPresetsUnselected {
            get {
                return ResourceManager.GetString("TextPresetsUnselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proceed.
        /// </summary>
        internal static string TextProceed {
            get {
                return ResourceManager.GetString("TextProceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload.
        /// </summary>
        internal static string TextReload {
            get {
                return ResourceManager.GetString("TextReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        internal static string TextRemove {
            get {
                return ResourceManager.GetString("TextRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string TextReset {
            get {
                return ResourceManager.GetString("TextReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs:.
        /// </summary>
        internal static string TextRuns {
            get {
                return ResourceManager.GetString("TextRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan.
        /// </summary>
        internal static string TextScan {
            get {
                return ResourceManager.GetString("TextScan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SHIFT.
        /// </summary>
        internal static string TextShift {
            get {
                return ResourceManager.GetString("TextShift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string TextStart {
            get {
                return ResourceManager.GetString("TextStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string TextStop {
            get {
                return ResourceManager.GetString("TextStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Elapsed:.
        /// </summary>
        internal static string TextTimeElapsed {
            get {
                return ResourceManager.GetString("TextTimeElapsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MacroUO.
        /// </summary>
        internal static string TextTitle {
            get {
                return ResourceManager.GetString("TextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top Most.
        /// </summary>
        internal static string TextTopMost {
            get {
                return ResourceManager.GetString("TextTopMost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Runs:.
        /// </summary>
        internal static string TextTotalRuns {
            get {
                return ResourceManager.GetString("TextTotalRuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transparency.
        /// </summary>
        internal static string TextTransparency {
            get {
                return ResourceManager.GetString("TextTransparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        internal static string TextUnhandledException {
            get {
                return ResourceManager.GetString("TextUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown exception has occurred and the application must be terminated..
        /// </summary>
        internal static string TextUnknownException {
            get {
                return ResourceManager.GetString("TextUnknownException", resourceCulture);
            }
        }
    }
}
